Repository theforeman/hammer-cli, pull requests merged in 2018-12, with the labels that each got.

#296 Update rpm names to use tfm
  doc/installation_rpm.md
Labels: Needs testing, Not yet reviewed

#295 Fixes #25438 - hammer -h does work with --output json, csv, yaml
  lib/hammer_cli/exception_handler.rb
  lib/hammer_cli/output/adapter/csv.rb
  lib/hammer_cli/output/adapter/tree_structure.rb
  test/unit/exception_handler_test.rb
  test/unit/output/adapter/abstract_test.rb
  test/unit/output/adapter/base_test.rb
  test/unit/output/adapter/csv_test.rb
  test/unit/output/adapter/json_test.rb
  test/unit/output/adapter/table_test.rb
  test/unit/output/adapter/yaml_test.rb
Labels: Needs testing

#242 Fixes #19574 - Validator uses options from option collector
  doc/creating_commands.md
  lib/hammer_cli.rb
  lib/hammer_cli/abstract.rb
  lib/hammer_cli/help/definition.rb
  lib/hammer_cli/options/option_collector.rb
  lib/hammer_cli/options/option_processor.rb
  lib/hammer_cli/options/processor_list.rb
  lib/hammer_cli/options/sources/base.rb
  lib/hammer_cli/options/sources/command_line.rb
  lib/hammer_cli/options/sources/saved_defaults.rb
  lib/hammer_cli/options/validators/base.rb
  lib/hammer_cli/options/validators/dsl.rb
  lib/hammer_cli/options/validators/dsl_block_validator.rb
  lib/hammer_cli/output/definition.rb
  lib/hammer_cli/utils.rb
  lib/hammer_cli/validator.rb
  test/unit/abstract_test.rb
  test/unit/options/option_collector_test.rb
  test/unit/options/processor_list_test.rb
  test/unit/options/validators/dsl_test.rb
  test/unit/utils_test.rb
Labels: Demo worthy, Ready for merge

#297 Refs #25724 - Fixed instructions in i18n docs
  doc/i18n.md
Labels: Needs testing, Not yet reviewed
