Repository theforeman/hammer-cli, pull requests merged in 2018-11, with the labels that each got.

#277 Fixes #21633 - Allow modification of additional help texts
  doc/developer_docs.md
  doc/help_modification.md
  lib/hammer_cli/abstract.rb
  lib/hammer_cli/help/definition.rb
  lib/hammer_cli/help/definition/abstract_item.rb
  lib/hammer_cli/help/definition/list.rb
  lib/hammer_cli/help/definition/section.rb
  lib/hammer_cli/help/definition/text.rb
  lib/hammer_cli/help/text_builder.rb
  test/unit/help/definition/abstract_item_test.rb
  test/unit/help/definition/list_test.rb
  test/unit/help/definition/section_test.rb
  test/unit/help/definition/text_test.rb
  test/unit/help/definition_test.rb
  test/unit/help/text_builder_test.rb
Labels: Demo worthy, Needs testing

#293 Fixes #25307 - Add ability to disable defaults
  bin/hammer
  config/cli_config.template.yml
  lib/hammer_cli/abstract.rb
  lib/hammer_cli/context.rb
  lib/hammer_cli/defaults.rb
  lib/hammer_cli/main.rb
  lib/hammer_cli/settings.rb
  test/unit/abstract_test.rb
  test/unit/settings_test.rb
Labels: Ready for merge

#294 Refs #24489 - Helper for editing text in editor
  lib/hammer_cli/utils.rb
Labels: Needs testing

#275 Fixes #21634 - Allows modification of output fields
  doc/commands_modification.md
  doc/developer_docs.md
  lib/hammer_cli/abstract.rb
  lib/hammer_cli/i18n.rb
  lib/hammer_cli/output/definition.rb
  lib/hammer_cli/output/dsl.rb
  lib/hammer_cli/output/fields.rb
  test/unit/output/definition_test.rb
Labels: Demo worthy
