Repository theforeman/hammer-cli, pull requests merged in 2018-02, with the labels that each got.

#270 Refs #22554 - Pin clamp version to < 1.2.0
  hammer_cli.gemspec
Labels: Ready for merge

#266 Refs #7451 - tests for message formats
  lib/hammer_cli/testing/messages.rb
  test/unit/messages_test.rb
Labels: Needs testing, Not yet reviewed

#257 Fixes #18532 - Better help for unsupported hammer commands
  lib/hammer_cli/apipie/command.rb
  test/unit/apipie/command_test.rb
Labels: Needs testing
