Repository theforeman/hammer-cli, pull requests merged in 2018-09, with the labels that each got.

#282 Bump clamp dep to >=1.1
  hammer_cli.gemspec
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#281 Fixes #17010 - Hammer JSON output uses inconsistent capitalization
  config/cli_config.template.yml
  lib/hammer_cli/context.rb
  lib/hammer_cli/output/adapter/json.rb
  lib/hammer_cli/output/adapter/tree_structure.rb
  lib/hammer_cli/output/adapter/yaml.rb
  lib/hammer_cli/utils.rb
  test/unit/output/adapter/json_test.rb
  test/unit/output/adapter/yaml_test.rb
  test/unit/utils_test.rb
Labels: Demo worthy

#288 Fixes #24980 - enable formatters in json structured output
  lib/hammer_cli/output/adapter/tree_structure.rb
Labels: Needs testing, Not yet reviewed
