Repository theforeman/hammer-cli, pull requests merged in 2021-08, with the labels that each got.

#350 Fixes #32783 - Extract descs to option details section
  lib/hammer_cli/abstract.rb
  lib/hammer_cli/apipie/command.rb
  lib/hammer_cli/help/builder.rb
  lib/hammer_cli/options/normalizers.rb
  lib/hammer_cli/options/option_definition.rb
  lib/hammer_cli/options/option_family.rb
  test/unit/abstract_test.rb
  test/unit/help/builder_test.rb
Labels: Needs testing, Not yet reviewed

#351 Fixes #33225 - Show depr warning only on option usage
  lib/hammer_cli/options/option_definition.rb
  test/unit/options/option_definition_test.rb
Labels: Needs testing, Not yet reviewed

#352 Fixes #33226 - Make API docs params to be the main options
  doc/creating_commands.md
  lib/hammer_cli/abstract.rb
  lib/hammer_cli/apipie/option_builder.rb
  lib/hammer_cli/apipie/option_definition.rb
  lib/hammer_cli/command_extensions.rb
  lib/hammer_cli/options/option_definition.rb
  lib/hammer_cli/options/option_family.rb
  test/unit/apipie/option_builder_test.rb
  test/unit/command_extensions_test.rb
Labels: Needs testing, Waiting on contributor

#348 Fixes #29093 - change from superficial copy to deep copy of fields
  lib/hammer_cli/output/field_filter.rb
Labels: Needs testing, Needs re-review

#353 Fixes #33259 - Don't store @context in field params
  lib/hammer_cli/output/adapter/abstract.rb
  lib/hammer_cli/output/adapter/base.rb
  lib/hammer_cli/output/adapter/tree_structure.rb
Labels: Needs testing, Not yet reviewed
